name: quizz
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk:  '>=2.19.2 <3.0.0'

dependencies:
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  
  google_nav_bar: ^5.0.6
  provider: ^6.1.1

cupertino_icons: ^1.0.6
provider:  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - img/


